---
title: "file.system"
author: "Anna Krystalli"
date: "24/01/2017"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# google drive folder

### **info/**

Information regarding the project and data, including admin. Includes action plans and literature reviews

- #### **invoicing/**
    - **Leave Sheet.gsheet:** googlesheet of booked holiday
    - **`invoice_id`-Bird Train Networks `purchase_order_id`:** copies of issued invoices.
- #### **Literature/**
  useful literature

### **inputs/**

- #### **data/**
  input data and metadata folder. Many input folders (`{rmacroRDM}`) are required by the functions of  `rmacroRDM`. Please do not alter the structure of these folders. For more details see [**rmacroRDM README**]()
    - **analytical/** 
        - **`master.csv`** : master (long) analytical dataset. Output of `wkf = "rmacroRDM"` in `match.workflow.R`
        - **`master wide.csv`** : master wide analytical dataset. Output of `wkf = "rmacroRDM"` in `match.workflow.R`
    - **metadata/ {rmarcroRDM folder}**
        - **`data_log.csv`** : metadata on raw datasets used to compile analytical
        - **`vnames.csv`** : metadata on raw data variable name matching to master
        - **`outliers.csv`** : table identifying outliers in duplicate `spp:var` entries
        - **`outlier_refs.csv`** : references supporting outlier identification
    - **pre/ {rmarcroRDM folder}** : contains `meta.var` folders, used to supply data to the `rmacroRDM` compilation functions. Dataset details can be found in `data_log.csv`.
        - **csv/**
        - **n/**
        - **notes/**
        - **observer/**
        - **qc/**
        - **ref/**
    - **post/ {rmarcroRDM folder}** : mirror folders of contents of **pre/** where post processed raw data is saved.
        - **csv/**
        - **n/**
        - **notes/**
        - **observer/**
        - **qc/**
        - **ref/**
    - **taxo/ {rmarcroRDM folder}** : contains taxonomic metadata.
        - **match data/** : data relating to the taxonomic match workflow. Includes:
            - `mmatch` and `mmatched` match output `.csv`s used to complete manual matching (deprecated: compiled to syn.links sheet). 
            - match `m .RData` object for each dataset matched to the project `spp.list` (ie in our case `D1` and the `tree`)
        - **synonyms/** : various synonym lists from which `syn.links` were extracted.
        - **100spp.csv** : list of 100 species for subset analysis.
        - **`an.ID`species_ranks.RData** : Loaded during `Phylonetworker_setup.R` in `wkf = "phylonetworker"`. Contains: 
            - **`spp.rank`** : rank of sum of each species datapoint contribution across all possible trait pairs.
        - **`dcode`_taxo.csv** : taxonomic data extracted from matched dataset `dcode`
        - **syn.links.csv** : synonym links lookup table. 
        - **TD_`an.ID`.Rdata** : table of taxonomic distincteness assessment outputs of trait data subset taxonomic makeup. Loaded during `Phylonetworker_setup.R` in `wkf = "phylonetworker"`.
    - **tree/** : contains files relating to the phylogenetic tree used in the analysis
        - **tree.RData** : tree used in analysis. Extracted from `Stage2_MayrAll_Hackett_set10_decisive.tre`.

### **outputs/**

- #### **data/**
    - **hrg/** : outputs of experimentation with fiting consensus hierarchical networks using the `hrg` package
    - **imputed_data/** : outputs of missing data imputation (for data preparation for `mgm` analysis) using different subsets of the original data. Subselection of data uses the ranks of variable and species to the total data pool and is accomplished by setting the **proportion of top var/species** to be used through parameters **`v`** and **`s`** respectively. 
        - file naming: **`an.ID`spp-v`v`-s`s`.Rdata** 
    - **match objects/** : m object resulting from processing and matching D1 data. {rmacroRDM}
    - **mgm/** : mixed graphical models. filenaming **`an.ID`-`v`-`s`-`min.n`-`min.cat`**. {mgm}
    - **networks/** : rnetcarto network outputs (as .Rdata as well as flat .csv). {phylonetworker}
        - Filenames: **`an.ID`_net_mn`min.n`_`log`**...
    - **phylocors/** : outputs of phylogenetically corrected trait pair correlation analysis. {phylonetworker} 
        - Filenames: **`an.ID`_phylocor_mn`min.n`_`log`_`pair.type`.Rdata**.   
        -   All `pair.type` results complied into **`all_phylocor_mn50_log_allDT.csv`**.
    - ##### **`master.rda`** : master object resulting from {rmacroRDM} workflow
    


- #### **reports/**
    - **progress reports/** : Rendered (html) progress reports 01-05 and associated files
    - **Results/** : Rendered (html) results reports
        - **Categorical_phylocors.nb.html** : Report on distribution of expected GKtau between pair of traits simulated from the phylogeny. 
        - **CorNetwork_plots.html** : early report ("nn" trait pairs only) on trait association network structure. Flat network plots.
        - **data_gap_eval.nb.html** : Report on data availability across traits. Include assessment of taxonomic distinctness of available trait data subsambles.
        - **hrg.html** : Demo of fitting a hierarchical graphical model.
        - **mgm_viz.html** : Visualisation of mixed graphical model (mgm) network
        - **Network_viz_`an.ID`.nb** : Vizualisation of phylonetworker networks
        
        
***

# github folder

<br>

### **R/**
  folder containing scripts either sourced by primary workflows, or relating to secondary workflows.  
  - **PhyloNetworker_functions.R** : functions sourced for a number of workflows (see [`load_environment](https://github.com/annakrystalli/bird_trait_networks/blob/master/R/load_environment.R) to process data, determine trait associations and fit and visualise networks.
  - **PhyloNetworker_setup.R** : workflow script, sourced to prepare data and associated objects for analysis.
   - **add amniote synonyms.R** : script to extract synonyms from supplied synonym list with `Amniote_Databsae`
   - **goodmankruskal.R** : GK  τ determination workflow for categorical variables.
   - **helper_functions.R** : project wide helper functions loaded during `project_ui`.
   - **impute_mgm.R** : script sourced during `mgm` wkf to impute missing data prior to mode fitting.
   - **load_dependencies.R** : script to load dependencies during `project_ui`.
   - **load_environment.R** : script to load wkf environment (functions and perform pre-processing) during `project_ui`.
   - **load_files.R** : loads `ref_system` files 
   - **load_global.R** :
   - **mgm_dataprep.R** :
   - **pkgs.R** :
   - **rerun_phylosig.R** :
   - **select_tree.R** :
   - **test_impute.R** :
   - **test_impute_functions.R** :
   - **test_impute_tools.R** :
   
   