---
title: "MCMCglmm sensitivity"
author: "Anna Krystalli"
date: "20 July 2016"
output: html_document
params:
  min.n: 
    label: "min.n"
    value: 10
    input: slider
    min: 0
    max: 100
  anID: 
    label: "Analysis ID"
    value: 10
    input: select
    choices: [all, 100spp]
  cut.off: 
    label: "corr cut.off"
    value: 0.35
    input: slider
    min: 0
    max: 1
  i: 
    label: "i"
    value: 2
    input: slider
    min: 0
    max: 100 
    

---

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
require(knitr)

knitr::read_chunk("~/Documents/workflows/bird_trait_networks/setup.R")
knitr::read_chunk("~/Documents/workflows/bird_trait_networks/PhyloNetworker_functions.R")
knitr::read_chunk("~/Documents/workflows/bird_trait_networks/tools/edge_explorer_setup.R")
```

```{r setup, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
```
```{r phylonetworker_functions, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=F, include=FALSE}
i <- params$i
an.ID <- params$anID
cut.off <- params$cut.off
min.n <- params$min.n
```

```{r setup_edge, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=F, include=FALSE}



x = cat.vg[i, 1:2]
var1 <- unlist(cat.vg[i, 1])
var2 <- unlist(cat.vg[i, 2])

levels1 <- getLevels(metadata, var1)
levels2 <- getLevels(metadata, var2)

levels1$n <- 0
levels2$n <- 0

table1 <- table(cat.dat[,var1])
levels1[match(names(table1), levels1$levels),"n"] <- table1

table2 <- table(cat.dat[,var2])
levels2[match(names(table2), levels2$levels),"n"] <- table2

results <- pglsPhyloCor(x = cat.vg[i, 1:2], data = cat.dat, 
                        tree = tree, log.vars = log.vars, 
                        datTypes = "cc", result = "model")


data.com <- cat.dat[complete.cases(cat.dat[, unlist(x)]),]

```

```{r}

i
x
levels1
levels2
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=F, fig.height= 12}


summary(results)

par(mfrow=c(8,2), mar=c(2,2,1,0))
plot(results$Sol, auto.layout=F)

```

